### ISSUE TITLE
restore telephony backup on A14

### ISSUE THREAD

**Issue by h1toru** [XayahSuSuSu/Android-DataBackup#277]
is there any way to restore telephony backups on Android 14? if it can be done manually, please tell me how to do it. thank you.

**Comment by watson96** [comment]
You can backup just the data of Phone and Messaging storage (com.android.providers.telephony), which is a system app. This is what all sms/call logs backup apps do I think

**Comment by watson96** [comment]
You restore it the same way? Restore just the data of those system apps you backed up and you should see your call logs and SMS in phone and messaging apps. Unless you're talking about telephony backup you took using the older 1.1.x version of DataBackup app (which never worked for me btw. I tap on the telephony section to back them up but nothing happens), this is how you backup AND **restore** telephony data on the newer versions of DataBackup. I would also like to warn you about how unreliable google backup is (at least for me) since for the past 4 clean flashes I have done, it never restored my SMS and contacts on an A14 QPR3 ROM even though I went through the whole restore steps during Setup wizard process. It used to work for me on older builds but stopped working now.

**Comment by h1toru** [comment]
yes, i'm talking about telephony backup in older version of DataBackup app (1.x.x). it couldn't be restored on A14 using the same version of DataBackup app (1.x.x), and i don't know any other way restore it on A14 because the backups is json(?) file, which is why i created this issue.

oh, that's a great info because this is my first time using google backup. but i'm planning to stay on A13 for quiet some time because i've encountered so many bugs/compatibility issues on A14 (especially QPR2/3); so i guess that wouldn't be a problem.

**Comment by XayahSuSuSu** [comment]
I'm planning to fix it on 1.0.x.

It needs time, at least for now, you can only downgrade to A13 to restore them.

**Comment by h1toru** [comment]
@XayahSuSuSu
thank you for your response.

**Comment by XayahSuSuSu** [comment]
BTW, what's the OS on your device?
I tested it on emulator of A14 and it worked well

**Comment by h1toru** [comment]
so far i have tried it on VoltageOS 3.4 (A14 QPR2) and AlphaDroid 2.0 (A14 QPR1). i don't think there is a problem with backup, but when i tried to restore, the popup to choose default sms app doesn't shows up.

**Comment by XayahSuSuSu** [comment]
[DataBackup-1.0.1-alpha06-arm64-v8a-foss-release.zip](https://github.com/user-attachments/files/16529168/DataBackup-1.0.1-alpha06-arm64-v8a-foss-release.zip)

@h1toru Can you test it?

**Comment by XayahSuSuSu** [comment]
Should be fixed in https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.0.1

**Comment by h1toru** [comment]
i've tested it on VoltageOS 3.4 (A14 QPR2), i can confirm it works. thank you for your work. @XayahSuSuSu

**Comment by watson96** [comment]
Just to confirm @XayahSuSuSu does backing up work as well on A14 with this new release you gave above? Because it didn't work before for me on VoltageOS A14 QPR2 or QPR3.

**Comment by XayahSuSuSu** [comment]
> Just to confirm @XayahSuSuSu does backing up work as well on A14 with this new release you gave above? Because it didn't work before for me on VoltageOS A14 QPR2 or QPR3.

It should work well, I tested on ColorOS 14.1 (Android 14)
